version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_nest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: movie_management
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_nest
    restart: always
    ports:
      - '8080:80' # Puedes cambiar el puerto 8080 si lo necesitas
    environment:
      PGADMIN_DEFAULT_EMAIL: emiliano.garcia96@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  postgres_data:
